### ISSUE TITLE
Data Analysis Lifecycle

### ISSUE THREAD

**Issue by rossellaaversa** [Materials-Data-Science-and-Informatics/MDMC-NEP-top-level-ontology#22]
In the general sense, the steps of the Data Analysis Lifecycle can be combined in chains in different order, really dependent on the use case. 
It's difficult for the ontology to keep track of all the possible cases. 
Either we try to keep it more general (having "Data Analysis Lifecycle steps" and "intermediate results") or we try to cover the most common cases, just to ensure that something is not wrong. 
For instance: 

**data processing:** 
- input: raw data or processed data or analysed data
- output: processed data
- using: data processing software

**data analysis:**
- input: raw data or processed data or analysed data
- output: analysed data
- using: data analysis software

**data interpretation:**
- input: raw data or processed data or analysed data
- output: results, conclusions, inference, ... and possibly analysed data

This can be simplified (checking the appropriate definitions):

**data processing:** 
- input: research data
- output: research data
- using: data analysis software

**data analysis:**
- input: research data
- output: research data
- using: data analysis software

**data interpretation:**
- input: research data
- output: results, conclusions, inference, ... and possibly analysed data

With this second case, what we have it that the Data Analysis Lifecycle has: 
- input: research data
- output: results, conclusions, inference, ... and possibly analysed data
- using: data analysis software

independently of which steps and on which order.

**Comment by az-ihsan** [comment]
> This can be simplified (checking the appropriate definitions):
> 
> **data processing:**
> 
> * input: research data
> * output: research data
> * using: data analysis software
I would say, since we already have `ProcessesData` as subclass of `ResearchData` we can put `ProcessesData` as output of `DataProcessing` but you are right, we should strictly put the input only to `ResearchData` which could be `ProcessedData`, `AnalyzedData`, `ReferenceData`, etc.  

This applies to other DataAnalysisLifeCycle member. 

How about that?

**Comment by EOsmenaj** [comment]
Hi,
just to share with you some definitions that I found really interesting: 

**Research Data** are defined as all information collected, created, or obtained from third 
parties by researchers to be analyzed with the purpose of generating, verifying and validating 
original scientific claims, irrespective of their form or the method of data collection. They can 
be raw, processed to a greater or lesser extent, or analyzed, and can adopt a digital or nondigital form. 


**Raw Data**: refers to the unprocessed source data, i.e. research data before being processed
or manipulated for analysis. Raw data are the original data obtained directly from an
instrument, a survey, the internet, or another source.

**Processed Data**: these are the research data resulting from any kind of processing or
manipulation of raw data – however minimal – in order to prepare them for analysis.
Examples of processed data are anonymized data (which no longer contain personal details),
cleaned data, annotated data, etc.

**Analyzed Data**: these are research data resulting from the analysis of the processed data and 
which can be incorporated or converted into graphs, tables or charts

Source: https://www.ugent.be/en/research/datamanagement/policies/rdm-policy.pdf

**Comment by EOsmenaj** [comment]
And these from another source: https://vocabularies.cessda.eu/vocabulary/LifecycleEventType?lang=en 

**DataProcessing**
Changes, additions or deletions brought to the data at any point in time after collection.

_- DataProcessing.Coding_
- Converting raw data into machine-readable codes.
   
_- Data processing: Classification_
  Documenting the meaning/substance of coded data.

_- Data processing: Transcriptions of interviews_
- Transferring video- or audio-taped data into written form.

_- Data processing: Weighting_
- Calculating weight variables and adding them to the data.

_- Data processing: Aggregation_
- Calculating cumulative measures of individual-level data or microdata.

_- Data processing: Composite measures_
- Calculating scales, indexes, or typologies and adding them to the data.

_- Data processing: Derivation_
- Calculating new variables from measured variables, usually by recodes.

_- Data processing: Quality checks_
- Checks for consistency, undocumented codes, missing data representation, etc.

_- Data processing: Data integration_
- Creating complex datasets by merging related data, for example, hierarchical datasets with multiple but related analysis units, or multiple-wave datasets, or data collected in different countries for a cross-national study, etc.

_- Data processing: Disclosure limitation_
- Editing the data to prevent identification of subjects, for example, performing anonymization measures like recoding or top-coding sensitive variables like income levels, suppressing some geographic indicators, or replacing personal names with pseudonyms and/or categorizing background or demographic information in qualitative data.

_- Data processing: Imputation_
- Replacing missing data points with values calculated according to an imputation technique.

**Comment by rossellaaversa** [comment]
- Nice definition of Reference Data can be taken from the definition by @EOsmenaj 
- Nice definition of Processed Data
- We agree on having just one definition for Data Analysis Software, as it is used also in Data Processing
- TODO for @rossellaaversa

**Comment by az-ihsan** [comment]
When we define `ResearchData prov:wasGeneratedBy DataAnalysisLifeCycle`, actually there is one catch because there is `RawData subclass of ResearchData`. It infers that `RawData prov:wasGenerated DataAnalysisLifeCycle` which is wrong according to definition we have that `RawData prov:wasGeneratedBy Measurement`.

i would suggest instead of `ResearchData prov:wasGeneratedBy DataAnalysisLifeCycle`, we can specify/add to `ProcessedData, AnalysedData, DataInterpretationConclusion prov:wasGeneratedBy DataAnalysisLifeCycle`

**Comment by az-ihsan** [comment]
> 

Could you formulate the `ReferenceData` definition from this?

**Comment by rossellaaversa** [comment]
Some suggestions to answer to the questions by @az-ihsan on Miro: 

1. just simply taking the third-party data that is not done in this study?
In our context, `ReferenceData` is `ResearchData` which is not produced during the current `Study`, used as reference to compare and/or validate the output of the `Study`, typically during the `Data Analysis Lifecycle`. 

2. do comparisons with analysed data that is made for reference data? 
Depending on the steps of the `Data Analysis Lifecycle`, it can be used for comparison during `Data Processing` or `Data Analysis` or `Data Interpretation`, we cannot say it in advance. 
As relationships, we can use the Controlled List Values offered by DataCite: 

- IsCitedBy
- Cites
- IsSupplementTo
- IsSupplementedBy
- IsContinuedBy 
- Continues  
- IsDescribedBy  
- Describes  
- HasMetadata  
- IsMetadataFor  
- HasVersion  
- IsVersionOf  
- IsNewVersionOf  
- IsPreviousVersionOf  
- IsPartOf  
- HasPart  
- IsReferencedBy  
- References  
- IsDocumentedBy  
- Documents  
- IsCompiledBy  
- Compiles  
- IsVariantFormOf  
- IsOriginalFormOf  
- IsIdenticalTo  
- IsReviewedBy  
- Reviews  
- IsDerivedFrom  
- IsSourceOf  
- IsRequiredBy  
- Requires  
- IsObsoletedBy  
- Obsoletes

**Comment by rossellaaversa** [comment]
Experiment: all the measurements from 1998 to 2019
Measurement: more or less one measurement per day (@mpanighel  to clarify further), rather than a measurement for each material

**Comment by rossellaaversa** [comment]
> * Nice definition of Reference Data can be taken from the definition by @EOsmenaj
> * Nice definition of Processed Data
> * We agree on having just one definition for Data Analysis Software, as it is used also in Data Processing.
> * Software may include two types: Data Analysis Software and Data Acquisition Software. This means that we cannot simply the name --> let's stay with Data Analysis Software, even if the name does not fit the processing
> * TODO for @rossellaaversa

Suggested definition of Data Analysis Software:  software used for each of the processes included in the Data Analysis Lifecycle (possibly including data rendering, visualisation, plotting) and yelling to Research Data as an output. If software is used for simulations (computer Experiments), it is considered an Instrument and should be described as such.

**Comment by az-ihsan** [comment]
> > * Nice definition of Reference Data can be taken from the definition by @EOsmenaj
> > * Nice definition of Processed Data
> > * We agree on having just one definition for Data Analysis Software, as it is used also in Data Processing.
> > * Software may include two types: Data Analysis Software and Data Acquisition Software. This means that we cannot simply the name --> let's stay with Data Analysis Software, even if the name does not fit the processing
> > * TODO for @rossellaaversa
> 
> Suggested definition of Data Analysis Software: software used on Research Data during each of the processes included in the Data Analysis Lifecycle (possibly including data rendering, visualisation, plotting) and yelding to Research Data as an output. Depending on the research context, Data Analysis Software can be used during Data Processing, Data Analysis or Data Interpretation, taking as input Raw Data, Processed Data or Analysed Data respectively, and giving as output Processed Data, Analysed Data or conclusions, respectively. If software is used to perform simulations and to generate Raw Data (computer Experiments), it is considered an Instrument and should be described as such.

Shall i update now according to this new definition?

**Comment by az-ihsan** [comment]
implemented issue closed
